version: "3.4"
services:
  vue-vite-node:  #feel free to use: docker compose logs node
    container_name: vue-vite-node
    image: vue-vite-node
    build:  
          context: .
          dockerfile: ./docker/node/Dockerfile    
    working_dir: /var/www/vue-vite   
    ports:
      - "5173:5173" #8000?   
    volumes:
      - .:/var/www/vue-vite
    tty: true #pseudo-terminal
    networks:
            - vue-vite-network

networks:
    vue-vite-network:
        driver: bridge
