version: "3.4"
services:
  vvd-vite:
    #feel free to use: docker compose logs node
    container_name: vvd-vite
    image: vvd-vite
    env_file: .env # .env file should be used only for variables that the yaml parser needs       
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        - ARG_WORKDIR=${ENV_VITE_WORKDIR}
        - ARG_USER=${ENV_VITE_USER}
    #working_dir: ${ENV_VITE_WORKDIR}  in node/Dockerfile?
    ports:
      - "5173:5173" #8000?   
    volumes:
      - ./vvd:${ENV_VITE_WORKDIR}
    tty: true #pseudo-terminal
    networks:
      - vvd-network

  vvd-nginx:
    container_name: vvd-nginx
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - '443:443'
    volumes:
      - ./vvd/dist:${ENV_FRONTEND_WORKDIR}:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl
    entrypoint: [ "nginx-debug", "-g", "daemon off;" ]
    networks:
      - vvd-network

networks:
  vvd-network:
    driver: bridge
